/* I/Oポートのレジスタ */
#define P1DDR  (*(volatile unsigned char  *)0xFEE000)
#define P2DDR  (*(volatile unsigned char  *)0xFEE001)
#define P3DDR  (*(volatile unsigned char  *)0xFEE002)
#define P4DDR  (*(volatile unsigned char  *)0xFEE003)
#define P5DDR  (*(volatile unsigned char  *)0xFEE004)
#define P6DDR  (*(volatile unsigned char  *)0xFEE005)
#define P8DDR  (*(volatile unsigned char  *)0xFEE007)
#define P9DDR  (*(volatile unsigned char  *)0xFEE008)
#define PADDR  (*(volatile unsigned char  *)0xFEE009)
#define PBDDR  (*(volatile unsigned char  *)0xFEE00A)
#define P1DR   (*(volatile unsigned char  *)0xFFFFD0)
#define P2DR   (*(volatile unsigned char  *)0xFFFFD1)
#define P3DR   (*(volatile unsigned char  *)0xFFFFD2)
#define P4DR   (*(volatile unsigned char  *)0xFFFFD3)
#define P5DR   (*(volatile unsigned char  *)0xFFFFD4)
#define P6DR   (*(volatile unsigned char  *)0xFFFFD5)
#define P7DR   (*(volatile unsigned char  *)0xFFFFD6)
#define P8DR   (*(volatile unsigned char  *)0xFFFFD7)
#define P9DR   (*(volatile unsigned char  *)0xFFFFD8)
#define PADR   (*(volatile unsigned char  *)0xFFFFD9)
#define PBDR   (*(volatile unsigned char  *)0xFFFFDA)
#define P2PCR  (*(volatile unsigned char  *)0xFEE03C)
#define P4PCR  (*(volatile unsigned char  *)0xFEE03E)
#define P5PCR  (*(volatile unsigned char  *)0xFEE03F)

/* タイマの共通レジスタ */
#define TSTR   (*(volatile unsigned char  *)0xFFFF60)
#define TSNC   (*(volatile unsigned char  *)0xFFFF61)
#define TMDR   (*(volatile unsigned char  *)0xFFFF62)
#define TOLR   (*(volatile unsigned char  *)0xFFFF63)
#define TISRA  (*(volatile unsigned char  *)0xFFFF64)
#define TISRB  (*(volatile unsigned char  *)0xFFFF65)
#define TISRC  (*(volatile unsigned char  *)0xFFFF66)
/* タイマ0の専用レジスタ */
#define TCR0   (*(volatile unsigned char  *)0xFFFF68)
#define TIOR0  (*(volatile unsigned char  *)0xFFFF69)
#define TCNT0  (*(volatile unsigned short *)0xFFFF6A)
#define GRA0   (*(volatile unsigned short *)0xFFFF6C)
#define GRB0   (*(volatile unsigned short *)0xFFFF6E)
/* タイマ1の専用レジスタ */
#define TCR1   (*(volatile unsigned char  *)0xFFFF70)
#define TIOR1  (*(volatile unsigned char  *)0xFFFF71)
#define TCNT1  (*(volatile unsigned short *)0xFFFF72)
#define GRA1   (*(volatile unsigned short *)0xFFFF74)
#define GRB1   (*(volatile unsigned short *)0xFFFF76)
/* タイマ2の専用レジスタ */
#define TCR2   (*(volatile unsigned char  *)0xFFFF78)
#define TIOR2  (*(volatile unsigned char  *)0xFFFF79)
#define TCNT2  (*(volatile unsigned short *)0xFFFF7A)
#define GRA2   (*(volatile unsigned short *)0xFFFF7C)
#define GRB2   (*(volatile unsigned short *)0xFFFF7E)

/* A-Dコンバータのレジスタ */
#define ADDRA  (*(volatile unsigned short *)0xFFFFE0)
#define ADDRB  (*(volatile unsigned short *)0xFFFFE2)
#define ADDRC  (*(volatile unsigned short *)0xFFFFE4)
#define ADDRD  (*(volatile unsigned short *)0xFFFFE6)
#define ADCSR  (*(volatile unsigned char  *)0xFFFFE8)
#define ADCR   (*(volatile unsigned char  *)0xFFFFE9)

/* D-Aコンバータのレジスタ */
#define DADR0  (*(volatile unsigned char  *)0xFFFF9C)
#define DADR1  (*(volatile unsigned char  *)0xFFFF9D)
#define DACR   (*(volatile unsigned char  *)0xFFFF9E)
#define DASTCR (*(volatile unsigned char  *)0xFEE01A)
