/***********************************************************
**  H8/3067R I/O Register Address (Header File)           **
**  H8/3069R I/O Register Address (Header File)           **
***********************************************************/  

/* 入出力ポート*/
#define P1DDR   (*(volatile unsigned char   *)0xFEE000)
#define P2DDR   (*(volatile unsigned char   *)0xFEE001)
#define P3DDR   (*(volatile unsigned char   *)0xFEE002)
#define P4DDR   (*(volatile unsigned char   *)0xFEE003)
#define P5DDR   (*(volatile unsigned char   *)0xFEE004)
#define P6DDR   (*(volatile unsigned char   *)0xFEE005)
#define P8DDR   (*(volatile unsigned char   *)0xFEE007)
#define P9DDR   (*(volatile unsigned char   *)0xFEE008)
#define PADDR   (*(volatile unsigned char   *)0xFEE009)
#define PBDDR   (*(volatile unsigned char   *)0xFEE00A)
#define P2PCR   (*(volatile unsigned char   *)0xFEE03C)
#define P4PCR   (*(volatile unsigned char   *)0xFEE03E)
#define P5PCR   (*(volatile unsigned char   *)0xFEE03F)
#define P1DR    (*(volatile unsigned char   *)0xFFFFD0)
#define P2DR    (*(volatile unsigned char   *)0xFFFFD1)
#define P3DR    (*(volatile unsigned char   *)0xFFFFD2)
#define P4DR    (*(volatile unsigned char   *)0xFFFFD3)
#define P5DR    (*(volatile unsigned char   *)0xFFFFD4)
#define P6DR    (*(volatile unsigned char   *)0xFFFFD5)
#define P7DR    (*(volatile unsigned char   *)0xFFFFD6)
#define P8DR    (*(volatile unsigned char   *)0xFFFFD7)
#define P9DR    (*(volatile unsigned char   *)0xFFFFD8)
#define PADR    (*(volatile unsigned char   *)0xFFFFD9)
#define PBDR    (*(volatile unsigned char   *)0xFFFFDA)
/* システム制御*/
#define MDCR    (*(volatile unsigned char   *)0xFEE011)
#define SYSCR   (*(volatile unsigned char   *)0xFEE012)
#define DIVCR   (*(volatile unsigned char   *)0xFEE01B)
#define MSTCRH  (*(volatile unsigned char   *)0xFEE01C)
#define MSTCRL  (*(volatile unsigned char   *)0xFEE01D)
/* バスコントローラ*/
#define BRCR    (*(volatile unsigned char   *)0xFEE013)
#define ADRCR   (*(volatile unsigned char   *)0xFEE01E)
#define CSCR    (*(volatile unsigned char   *)0xFEE01F)
#define ABWCR   (*(volatile unsigned char   *)0xFEE020)
#define ASTCR   (*(volatile unsigned char   *)0xFEE021)
#define WCRH    (*(volatile unsigned char   *)0xFEE022)
#define WCRL    (*(volatile unsigned char   *)0xFEE023)
#define BCR     (*(volatile unsigned char   *)0xFEE024)
/* 割込コントローラ*/
#define ISCR    (*(volatile unsigned char   *)0xFEE014)
#define IER     (*(volatile unsigned char   *)0xFEE015)
#define ISR     (*(volatile unsigned char   *)0xFEE016)
#define IPRA    (*(volatile unsigned char   *)0xFEE018)
#define IPRB    (*(volatile unsigned char   *)0xFEE019)
/* DRAMインターフェース*/
#define DRCRA   (*(volatile unsigned char   *)0xFEE026)
#define DRCRB   (*(volatile unsigned char   *)0xFEE027)
#define RTMCSR  (*(volatile unsigned char   *)0xFEE028)
#define RTCNT   (*(volatile unsigned char   *)0xFEE029)
#define RTCOR   (*(volatile unsigned char   *)0xFEE02A)
/* 16bitタイマ共通*/
#define TSTR    (*(volatile unsigned char   *)0xFFFF60)
#define TSNC    (*(volatile unsigned char   *)0xFFFF61)
#define TMDR    (*(volatile unsigned char   *)0xFFFF62)
#define TOLR    (*(volatile unsigned char   *)0xFFFF63)
#define TISRA   (*(volatile unsigned char   *)0xFFFF64)
#define TISRB   (*(volatile unsigned char   *)0xFFFF65)
#define TISRC   (*(volatile unsigned char   *)0xFFFF66)
/* 16bitタイマCH0*/
#define TCR0    (*(volatile unsigned char   *)0xFFFF68)
#define TIOR0   (*(volatile unsigned char   *)0xFFFF69)
#define TCNT0   (*(volatile unsigned short  *)0xFFFF6A)
#define GRA0    (*(volatile unsigned short  *)0xFFFF6C)
#define GRB0    (*(volatile unsigned short  *)0xFFFF6E)
/* 16bitタイマCH1*/
#define TCR1    (*(volatile unsigned char   *)0xFFFF70)
#define TIOR1   (*(volatile unsigned char   *)0xFFFF71)
#define TCNT1   (*(volatile unsigned short  *)0xFFFF72)
#define GRA1    (*(volatile unsigned short  *)0xFFFF74)
#define GRB1    (*(volatile unsigned short  *)0xFFFF76)
/* 16bitタイマCH2*/
#define TCR2    (*(volatile unsigned char   *)0xFFFF78)
#define TIOR2   (*(volatile unsigned char   *)0xFFFF79)
#define TCNT2   (*(volatile unsigned short  *)0xFFFF7A)
#define GRA2    (*(volatile unsigned short  *)0xFFFF7C)
#define GRB2    (*(volatile unsigned short  *)0xFFFF7E)
/* シリアルch0*/
#define SMR0    (*(volatile unsigned char   *)0xFFFFB0)
#define BRR0    (*(volatile unsigned char   *)0xFFFFB1)
#define SCR0    (*(volatile unsigned char   *)0xFFFFB2)
#define TDR0    (*(volatile unsigned char   *)0xFFFFB3)
#define SSR0    (*(volatile unsigned char   *)0xFFFFB4)
#define RDR0    (*(volatile unsigned char   *)0xFFFFB5)
#define SCMR0   (*(volatile unsigned char   *)0xFFFFB6)
/* シリアルch1*/
#define SMR1    (*(volatile unsigned char   *)0xFFFFB8)
#define BRR1    (*(volatile unsigned char   *)0xFFFFB9)
#define SCR1    (*(volatile unsigned char   *)0xFFFFBA)
#define TDR1    (*(volatile unsigned char   *)0xFFFFBB)
#define SSR1    (*(volatile unsigned char   *)0xFFFFBC)
#define RDR1    (*(volatile unsigned char   *)0xFFFFBD)
#define SCMR1   (*(volatile unsigned char   *)0xFFFFBE)
/* シリアルch2*/
#define SMR2    (*(volatile unsigned char   *)0xFFFFC0)
#define BRR2    (*(volatile unsigned char   *)0xFFFFC1)
#define SCR2    (*(volatile unsigned char   *)0xFFFFC2)
#define TDR2    (*(volatile unsigned char   *)0xFFFFC3)
#define SSR2    (*(volatile unsigned char   *)0xFFFFC4)
#define RDR2    (*(volatile unsigned char   *)0xFFFFC5)
#define SCMR2   (*(volatile unsigned char   *)0xFFFFC6)
/* DAコンバータ*/
#define DASTCR  (*(volatile unsigned char   *)0xFEE01A)
#define DADR0   (*(volatile unsigned char   *)0xFFFF9C)
#define DADR1   (*(volatile unsigned char   *)0xFFFF9D)
#define DACR    (*(volatile unsigned char   *)0xFFFF9E)
/* ADコンバータ*/
#define ADDRAH  (*(volatile unsigned char   *)0xFFFFE0)
#define ADDRAL  (*(volatile unsigned char   *)0xFFFFE1)
#define ADDRBH  (*(volatile unsigned char   *)0xFFFFE2)
#define ADDRBL  (*(volatile unsigned char   *)0xFFFFE3)
#define ADDRCH  (*(volatile unsigned char   *)0xFFFFE4)
#define ADDRCL  (*(volatile unsigned char   *)0xFFFFE5)
#define ADDRDH  (*(volatile unsigned char   *)0xFFFFE6)
#define ADDRDL  (*(volatile unsigned char   *)0xFFFFE7)
#define ADCSR   (*(volatile unsigned char   *)0xFFFFE8)
#define ADCR    (*(volatile unsigned char   *)0xFFFFE9)
