/* I/Oポートのレジスタ */
#define P1DDR  (*(volatile unsigned char  *)0xEE000)
#define P2DDR  (*(volatile unsigned char  *)0xEE001)
#define P3DDR  (*(volatile unsigned char  *)0xEE002)
#define P4DDR  (*(volatile unsigned char  *)0xEE003)
#define P5DDR  (*(volatile unsigned char  *)0xEE004)
#define P6DDR  (*(volatile unsigned char  *)0xEE005)
#define P8DDR  (*(volatile unsigned char  *)0xEE007)
#define P9DDR  (*(volatile unsigned char  *)0xEE008)
#define PADDR  (*(volatile unsigned char  *)0xEE009)
#define PBDDR  (*(volatile unsigned char  *)0xEE00A)
#define P1DR   (*(volatile unsigned char  *)0xFFFD0)
#define P2DR   (*(volatile unsigned char  *)0xFFFD1)
#define P3DR   (*(volatile unsigned char  *)0xFFFD2)
#define P4DR   (*(volatile unsigned char  *)0xFFFD3)
#define P5DR   (*(volatile unsigned char  *)0xFFFD4)
#define P6DR   (*(volatile unsigned char  *)0xFFFD5)
#define P7DR   (*(volatile unsigned char  *)0xFFFD6)
#define P8DR   (*(volatile unsigned char  *)0xFFFD7)
#define P9DR   (*(volatile unsigned char  *)0xFFFD8)
#define PADR   (*(volatile unsigned char  *)0xFFFD9)
#define PBDR   (*(volatile unsigned char  *)0xFFFDA)
#define P2PCR  (*(volatile unsigned char  *)0xEE03C)
#define P4PCR  (*(volatile unsigned char  *)0xEE03E)
#define P5PCR  (*(volatile unsigned char  *)0xEE03F)

/* タイマの共通レジスタ */
#define TSTR   (*(volatile unsigned char  *)0xFFF60)
#define TSNC   (*(volatile unsigned char  *)0xFFF61)
#define TMDR   (*(volatile unsigned char  *)0xFFF62)
#define TOLR   (*(volatile unsigned char  *)0xFFF63)
#define TISRA  (*(volatile unsigned char  *)0xFFF64)
#define TISRB  (*(volatile unsigned char  *)0xFFF65)
#define TISRC  (*(volatile unsigned char  *)0xFFF66)
/* タイマ0の専用レジスタ */
#define TCR0   (*(volatile unsigned char  *)0xFFF68)
#define TIOR0  (*(volatile unsigned char  *)0xFFF69)
#define TCNT0  (*(volatile unsigned short *)0xFFF6A)
#define GRA0   (*(volatile unsigned short *)0xFFF6C)
#define GRB0   (*(volatile unsigned short *)0xFFF6E)
/* タイマ1の専用レジスタ */
#define TCR1   (*(volatile unsigned char  *)0xFFF70)
#define TIOR1  (*(volatile unsigned char  *)0xFFF71)
#define TCNT1  (*(volatile unsigned short *)0xFFF72)
#define GRA1   (*(volatile unsigned short *)0xFFF74)
#define GRB1   (*(volatile unsigned short *)0xFFF76)
/* タイマ2の専用レジスタ */
#define TCR2   (*(volatile unsigned char  *)0xFFF78)
#define TIOR2  (*(volatile unsigned char  *)0xFFF79)
#define TCNT2  (*(volatile unsigned short *)0xFFF7A)
#define GRA2   (*(volatile unsigned short *)0xFFF7C)
#define GRB2   (*(volatile unsigned short *)0xFFF7E)

/* A-Dコンバータのレジスタ */
#define ADDRA  (*(volatile unsigned short *)0xFFFE0)
#define ADDRB  (*(volatile unsigned short *)0xFFFE2)
#define ADDRC  (*(volatile unsigned short *)0xFFFE4)
#define ADDRD  (*(volatile unsigned short *)0xFFFE6)
#define ADCSR  (*(volatile unsigned char  *)0xFFFE8)
#define ADCR   (*(volatile unsigned char  *)0xFFFE9)

/* D-Aコンバータのレジスタ */
#define DADR0  (*(volatile unsigned char  *)0xFFF9C)
#define DADR1  (*(volatile unsigned char  *)0xFFF9D)
#define DACR   (*(volatile unsigned char  *)0xFFF9E)
#define DASTCR (*(volatile unsigned char  *)0xEE01A)
