/*--------------------------------------------------------------------*/
/* H8S,H8/300 SERIES C Compiler Ver. 1.0                              */
/* Copyright (C) 1994 Hitachi, Ltd.                                   */
/* Licensed Material of Hitachi,Ltd.                                  */
/*--------------------------------------------------------------------*/
/*****************************************************************/
/* SPEC ;                                                        */
/*   NAME = float :                                              */
/*   FUNC = limit about float type  and double type ;            */
/*                                                               */
/*                                                               */
/*   END ;                                                       */
/*****************************************************************/

#define FLT_RADIX             2
#define FLT_ROUNDS            1
#define FLT_GUARD             1
#define FLT_NORMALIZE         1
#define FLT_MAX 3.4028235677973364e+38f
#define FLT_MIN 7.0064923216240862e-46f
#define FLT_MAX_EXP         127
#define FLT_MIN_EXP       (-149)
#define FLT_MAX_10_EXP       38
#define FLT_MIN_10_EXP     (-44)
#define FLT_DIG               6
#define FLT_MANT_DIG         24
#define FLT_EXP_DIG           8
#define FLT_POS_EPS 5.9604648328104311e-8f
#define FLT_NEG_EPS 2.9802324164052156e-8f
#define FLT_POS_EPS_EXP    (-23)
#define FLT_NEG_EPS_EXP    (-24)

#define DBL_MAX 1.7976931348623158e+308
#define DBL_MIN 4.9406564584124655e-324
#define DBL_MAX_EXP        1023
#define DBL_MIN_EXP      (-1074)
#define DBL_MAX_10_EXP      308
#define DBL_MIN_10_EXP    (-323)
#define DBL_DIG              15
#define DBL_MANT_DIG         53
#define DBL_EXP_DIG          11
#define DBL_POS_EPS 1.1102230246251567e-16
#define DBL_NEG_EPS 5.5511151231257834e-17
#define DBL_POS_EPS_EXP    (-52)
#define DBL_NEG_EPS_EXP    (-53)

#define LDBL_MAX 1.7976931348623158e+308
#define LDBL_MIN 4.9406564584124655e-324
#define LDBL_MAX_EXP        1023
#define LDBL_MIN_EXP      (-1074)
#define LDBL_MAX_10_EXP      308
#define LDBL_MIN_10_EXP    (-323)
#define LDBL_DIG              15
#define LDBL_MANT_DIG         53
#define LDBL_EXP_DIG          11
#define LDBL_POS_EPS 1.1102230246251567e-16
#define LDBL_NEG_EPS 5.5511151231257834e-17
#define LDBL_POS_EPS_EXP    (-52)
#define LDBL_NEG_EPS_EXP    (-53)
