/*--------------------------------------------------------------------*/
/* H8S,H8/300 SERIES C Compiler Ver. 2.0                              */
/* Copyright (C) 1994,1996 Hitachi, Ltd.                              */
/* Licensed Material of Hitachi,Ltd.                                  */
/*--------------------------------------------------------------------*/
/*****************************************************************/
/* SPEC ;                                                        */
/*   NAME = no_float.h :                                         */
/*   FUNC =                                                      */
/*          ;                                                    */
/*   CLAS = UNIT ;                                               */
/*   END ;                                                       */
/*****************************************************************/

#define fprintf  _fprintf_lite
#define fscanf   _fscanf_lite
#define printf   _printf_lite
#define scanf    _scanf_lite
#define sprintf  _sprintf_lite
#define sscanf   _sscanf_lite
#define vfprintf _vfprintf_lite
#define vprintf  _vprintf_lite
#define vsprintf _vsprintf_lite

